# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proj_Exec_TimeStmp',
            fields=[
                ('timeStmpID', models.AutoField(primary_key=True, serialize=False)),
                ('startTimeStmp', models.DateTimeField()),
                ('endTimeStmp', models.DateTimeField()),
            ],
            options={
                'db_table': 'PROJ_EXEC_TIMESTMP',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'PROJECTS',
            },
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=1000)),
                ('query_sql', models.CharField(max_length=1000)),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='date published')),
            ],
            options={
                'db_table': 'QUERIES',
            },
        ),
        migrations.CreateModel(
            name='Site_Reports',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('patientCount', models.IntegerField()),
                ('exec_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingTool.Proj_Exec_TimeStmp')),
            ],
            options={
                'db_table': 'SITE_REPORTS',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('siteID', models.AutoField(primary_key=True, serialize=False)),
                ('siteName', models.CharField(max_length=1000)),
                ('project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingTool.Projects')),
            ],
            options={
                'db_table': 'SITES',
            },
        ),
        migrations.AddField(
            model_name='site_reports',
            name='site_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingTool.Sites'),
        ),
        migrations.AddField(
            model_name='proj_exec_timestmp',
            name='project_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportingTool.Projects'),
        ),
    ]
