# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=1000)),
                ('query_sql', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(default=datetime.date(2016, 8, 2), verbose_name='date published')),
            ],
        ),
    ]
