# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reportingTool', '0002_auto_20160802_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 2, 20, 38, 2, 118062, tzinfo=utc), verbose_name='date published'),
        ),
    ]
