# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingTool', '0003_auto_20160802_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
