# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportingTool', '0004_auto_20160802_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date published'),
        ),
    ]
